services:
  breadbox-server:
    image: breadbox:latest
    container_name: breadbox-server
    environment:
      NODE_ENV: production
      SCRIPT_PATH: "/recipes/server/server.js"
    ports:
      - "3000:3000"
    volumes:
      - ./fs:/recipes/fs
    networks:
      - breadbox

  breadbox-db:
    image: mongo:7
    container_name: breadbox-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - breadbox

volumes:
  mongodb:

networks:
  breadbox:
    driver: bridge
