services:
  breadbox-web-app:
    image: breadbox:latest
    container_name: breadbox-web-app
    working_dir: "/recipes/app"
    environment:
      NODE_ENV: development
      SCRIPT_PATH: "/recipes/app/node_modules/vite/bin/vite.js --host"
    ports:
      - "3000:5173"
    volumes:
      - ./app:/recipes/app
    networks:
      - breadbox

  breadbox-server:
    image: breadbox:latest
    container_name: breadbox-server
    environment:
      NODE_ENV: development
      SCRIPT_PATH: "/recipes/server/server.js"
    volumes:
      - ./fs:/recipes/fs
      - ./server:/recipes/server
    networks:
      - breadbox

  breadbox-db:
    image: mongo:7
    container_name: breadbox-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - breadbox

volumes:
  mongodb:
networks:
  breadbox:
    driver: bridge
