services:
  breadbox-web-app:
    image: breadbox:latest
    container_name: breadbox-web-app
    working_dir: "/recipes/app"
    environment:
      NODE_ENV: development
      breadboxPath: "/recipes/app/node_modules/vite/bin/vite.js --host"
    ports:
      - "5173:5173"
    volumes:
      - ./app:/recipes/app
    networks:
      - breadbox

  breadbox-server:
    image: breadbox:latest
    container_name: breadbox-server
    environment:
      NODE_ENV: development
      breadboxPath: "/recipes/server/server.js"
    ports:
      - "3000:3000"
    volumes:
      - ./fs:/recipes/fs
      - ./server:/recipes/server
    networks:
      - breadbox

  breadbox-db:
    image: mongo:7
    container_name: breadbox-db
      # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: af98132hkaskf91
    volumes:
      - mongodb:/data/db
    networks:
      - breadbox

volumes:
  mongodb:
networks:
  breadbox:
    driver: bridge
